### ISSUE TITLE
error: webtorrent is not defined

### ISSUE THREAD

**Issue by dasche** [DiegoRBaquero/PeerFast#2]
on latest firefox (windows), in web console an error is displayed: "webtorrent is not defined" and test never loads.

**Comment by DiegoRBaquero** [comment]
Is there anything else shown? PeerFast fetches webtorrent from jsdelivr, maybe you have it blocked?

**Comment by dasche** [comment]
ReferenceError: invalid assignment left-hand side.  webtorrent.min.js:7:4221
ReferenceError: WebTorrent is not defined. PeerFast:33:9 

I have nothing blocked.

**Comment by DiegoRBaquero** [comment]
that's really weird. I tested on Firefox MacOS, can't reproduce, but doesn't work anyways, ICE fails
