### ISSUE TITLE
Stuck at "Test is starting

### ISSUE THREAD

**Issue by erayrafet** [DiegoRBaquero/PeerFast#3]
Tested on Firefox 78 Dev and Chrome 84 Beta on Windows 10 and Chrome 84 Beta on Android.
![image](https://user-images.githubusercontent.com/34194191/84013011-094ae500-a981-11ea-86c2-2e730deac68e.png)

**Comment by rankun203** [comment]
@erayrafet Open your developer tools and check the console log, probably it fails to connect to the trackers (wss://xxx), change network environment and re-try.

**Comment by erayrafet** [comment]
It works well now.
